version: '3.8'

services:
  clippy-bot:
    build: .
    container_name: clippy-bot
    restart: unless-stopped
    command: ["python", "-m", "apps.clippy_bot.main"]
    environment:
      - CLIPPY_BOT_TOKEN=${CLIPPY_BOT_TOKEN}
      - CLIPPY_GUILD_ID=${CLIPPY_GUILD_ID:-}
      - CLIPPY_DEBUG=${CLIPPY_DEBUG:-false}
    volumes:
      - ./data/clippy:/app/data
    ports:
      - "8081:8080"  # Health check port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  music-bot:
    build: .
    container_name: music-bot
    restart: unless-stopped
    command: ["python", "-m", "apps.music_bot.main"]
    environment:
      - MUSIC_BOT_TOKEN=${MUSIC_BOT_TOKEN}
      - MUSIC_GUILD_ID=${MUSIC_GUILD_ID:-}
      - MUSIC_DEBUG=${MUSIC_DEBUG:-false}
    volumes:
      - ./data/music:/app/data
    ports:
      - "8082:8080"  # Health check port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Nginx reverse proxy for health checks
  nginx:
    image: nginx:alpine
    container_name: discord-bots-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - clippy-bot
      - music-bot
    profiles:
      - with-nginx

volumes:
  clippy-data:
  music-data: