global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Discord Bot Framework metrics
  - job_name: 'discord-bots'
    static_configs:
      - targets: ['mtg-card-bot:8080', 'clippy-bot:8080', 'music-bot:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-host:9323']

  # System metrics (if node_exporter is available)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']