apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: discord-bot-framework-production
  namespace: discord-bots-prod

bases:
- ../../base

namespace: discord-bots-prod

commonLabels:
  environment: production

images:
- name: ghcr.io/sawyer/discord-bot-framework
  newTag: v2.0.0

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

resources:
- namespace.yaml
- network-policy.yaml
- pod-disruption-budget.yaml

replicas:
- name: discord-bot-framework
  count: 2