version: "2"

# Linters configuration
linters:
  # Enable specific linters
  enable:
    # Core linters (enabled by default, but listing for clarity)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional security linters
    - gosec
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - gocritic
    - whitespace
    - wsl_v5
    # Performance linters
    - prealloc
    # Style linters
    - godot
    - revive
    # Error handling
    - errname
    - errorlint
    - wrapcheck
  disable:
    # Disable overly strict linters for Discord bot context
    - exhaustruct  # Too strict for configuration structs
    - varnamelen   # Short variable names are fine in limited scopes
    - ireturn      # Interface returns are sometimes necessary

# Run configuration
run:
  timeout: 5m
  go: '1.23'
  tests: true
  build-tags:
    - mage
  skip-dirs:
    - bin
    - cache
    - tmp
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

# Formatters configuration (v2 feature)
formatters:
  gofmt:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/dunamismax/MTG-Card-Bot

# Linter-specific settings
linters-settings:
  gosec:
    # Exclude some security checks that are false positives for bots
    excludes:
      - G404 # Use of weak random number generator is OK for non-crypto uses
  
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
  gocyclo:
    min-complexity: 15
  
  misspell:
    locale: US
    ignore-words:
      - mtg
      - scryfall
      - mana
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint
  
  
  revive:
    rules:
      - name: exported
        disabled: true  # We use other linters for this
      - name: package-comments
        disabled: true  # Not always needed for small packages
  
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
    ignorePackageGlobs:
      - github.com/pkg/errors
  
  errorlint:
    errorf: true
    asserts: true
    comparison: true

# Issues configuration
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false  # Show all issues, not just new ones
  fix: false  # Don't auto-fix issues
  
  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    # Exclude some issues in main.go (entry point)
    - path: main\.go
      linters:
        - gochecknoinits  # Init functions are OK in main
    
    # Exclude magic number checks for common Discord/HTTP values
    - text: "Magic number: (200|400|401|403|404|500|429|2000|8000|443|80)"
      linters:
        - gomnd
        - goconst

# Output configuration
output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

# Severity configuration
severity:
  default: error
  case-sensitive: false
  rules:
    - linters:
        - misspell
        - goconst
      severity: warning
    - linters:
        - gosec
        - errcheck
        - staticcheck
      severity: error