apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-bot-config
  labels:
    app: discord-bot-framework
data:
  # Global configuration
  LOG_LEVEL: "info"
  JSON_LOGGING: "true"
  METRICS_ENABLED: "true"
  METRICS_PORT: "8080"
  HEALTH_PORT: "8081"
  
  # MTG Card Bot configuration
  CACHE_TTL: "1h"
  CACHE_SIZE: "1000"
  REQUEST_TIMEOUT: "30s"
  MAX_RETRIES: "3"
  
  # Clippy Bot configuration
  RANDOM_RESPONSES: "true"
  RANDOM_INTERVAL: "45m"
  RANDOM_MESSAGE_DELAY: "3s"
  
  # Music Bot configuration
  MAX_QUEUE_SIZE: "100"
  INACTIVITY_TIMEOUT: "5m"
  VOLUME_LEVEL: "0.5"
  DATABASE_URL: "/app/data/music.db"