apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-bot-data
  labels:
    app: discord-bot-framework
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard